eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/api/payments/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/api/orders/bookOrder
